package com.example.eyeofthelaw.utils

object InflationIndex {
    val years = listOf(
        Years(
            year = "1371",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 1.4),
                Month(month = "اردیبهشت", inflationIndex = 1.4),
                Month(month = "خرداد", inflationIndex = 1.4),
                Month(month = "تیر", inflationIndex = 1.4),
                Month(month = "مرداد", inflationIndex = 1.5),
                Month(month = "شهریور", inflationIndex = 1.5),
                Month(month = "مهر", inflationIndex = 1.5),
                Month(month = "آبان", inflationIndex = 1.5),
                Month(month = "آذر", inflationIndex = 1.5),
                Month(month = "دی", inflationIndex = 1.6),
                Month(month = "بهمن", inflationIndex = 1.6),
                Month(month = "اسفند", inflationIndex = 1.6),
            ),
            inflationIndex = 1.48,
            percentageChanges = 25.0
        ),
        Years(
            year = "1372",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 1.7),
                Month(month = "اردیبهشت", inflationIndex = 1.7),
                Month(month = "خرداد", inflationIndex = 1.7),
                Month(month = "تیر", inflationIndex = 1.7),
                Month(month = "مرداد", inflationIndex = 1.7),
                Month(month = "شهریور", inflationIndex = 1.8),
                Month(month = "مهر", inflationIndex = 1.8),
                Month(month = "آبان", inflationIndex = 1.8),
                Month(month = "آذر", inflationIndex = 1.9),
                Month(month = "دی", inflationIndex = 1.9),
                Month(month = "بهمن", inflationIndex = 2.0),
                Month(month = "اسفند", inflationIndex = 2.1),
            ),
            inflationIndex = 1.814,
            percentageChanges = 22.6
        ),
        Years(
            year = "1373",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 2.1),
                Month(month = "اردیبهشت", inflationIndex = 2.2),
                Month(month = "خرداد", inflationIndex = 2.2),
                Month(month = "تیر", inflationIndex = 2.3),
                Month(month = "مرداد", inflationIndex = 2.3),
                Month(month = "شهریور", inflationIndex = 2.4),
                Month(month = "مهر", inflationIndex = 2.5),
                Month(month = "آبان", inflationIndex = 2.5),
                Month(month = "آذر", inflationIndex = 2.5),
                Month(month = "دی", inflationIndex = 2.6),
                Month(month = "بهمن", inflationIndex = 2.8),
                Month(month = "اسفند", inflationIndex = 3.0),
            ),
            inflationIndex = 2.465,
            percentageChanges = 35.9
        ),
        Years(
            year = "1374",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 3.2),
                Month(month = "اردیبهشت", inflationIndex = 3.5),
                Month(month = "خرداد", inflationIndex = 3.5),
                Month(month = "تیر", inflationIndex = 3.5),
                Month(month = "مرداد", inflationIndex = 3.5),
                Month(month = "شهریور", inflationIndex = 3.5),
                Month(month = "مهر", inflationIndex = 3.6),
                Month(month = "آبان", inflationIndex = 3.7),
                Month(month = "آذر", inflationIndex = 3.8),
                Month(month = "دی", inflationIndex = 4.0),
                Month(month = "بهمن", inflationIndex = 4.0),
                Month(month = "اسفند", inflationIndex = 4.1),
            ),
            inflationIndex = 3.665,
            percentageChanges = 48.7
        ),
        Years(
            year = "1375",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 4.4),
                Month(month = "اردیبهشت", inflationIndex = 4.4),
                Month(month = "خرداد", inflationIndex = 4.4),
                Month(month = "تیر", inflationIndex = 4.4),
                Month(month = "مرداد", inflationIndex = 4.4),
                Month(month = "شهریور", inflationIndex = 4.4),
                Month(month = "مهر", inflationIndex = 4.5),
                Month(month = "آبان", inflationIndex = 4.6),
                Month(month = "آذر", inflationIndex = 4.6),
                Month(month = "دی", inflationIndex = 4.7),
                Month(month = "بهمن", inflationIndex = 4.8),
                Month(month = "اسفند", inflationIndex = 4.8),
            ),
            inflationIndex = 4.52,
            percentageChanges = 23.3
        ),
        Years(
            year = "1376",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 5.0),
                Month(month = "اردیبهشت", inflationIndex = 5.1),
                Month(month = "خرداد", inflationIndex = 5.1),
                Month(month = "تیر", inflationIndex = 5.1),
                Month(month = "مرداد", inflationIndex = 5.2),
                Month(month = "شهریور", inflationIndex = 5.2),
                Month(month = "مهر", inflationIndex = 5.2),
                Month(month = "آبان", inflationIndex = 5.3),
                Month(month = "آذر", inflationIndex = 5.4),
                Month(month = "دی", inflationIndex = 5.5),
                Month(month = "بهمن", inflationIndex = 5.6),
                Month(month = "اسفند", inflationIndex = 5.7),
            ),
            inflationIndex = 5.298,
            percentageChanges = 17.2
        ),
        Years(
            year = "1377",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 6.0),
                Month(month = "اردیبهشت", inflationIndex = 6.0),
                Month(month = "خرداد", inflationIndex = 6.0),
                Month(month = "تیر", inflationIndex = 6.0),
                Month(month = "مرداد", inflationIndex = 6.0),
                Month(month = "شهریور", inflationIndex = 6.1),
                Month(month = "مهر", inflationIndex = 6.2),
                Month(month = "آبان", inflationIndex = 6.3),
                Month(month = "آذر", inflationIndex = 6.5),
                Month(month = "دی", inflationIndex = 6.5),
                Month(month = "بهمن", inflationIndex = 6.7),
                Month(month = "اسفند", inflationIndex = 6.8),
            ),
            inflationIndex = 6.258,
            percentageChanges = 18.1
        ),
        Years(
            year = "1378",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 7.2),
                Month(month = "اردیبهشت", inflationIndex = 7.3),
                Month(month = "خرداد", inflationIndex = 7.3),
                Month(month = "تیر", inflationIndex = 7.3),
                Month(month = "مرداد", inflationIndex = 7.3),
                Month(month = "شهریور", inflationIndex = 7.4),
                Month(month = "مهر", inflationIndex = 7.5),
                Month(month = "آبان", inflationIndex = 7.5),
                Month(month = "آذر", inflationIndex = 7.7),
                Month(month = "دی", inflationIndex = 7.8),
                Month(month = "بهمن", inflationIndex = 7.9),
                Month(month = "اسفند", inflationIndex = 8.1),
            ),
            inflationIndex = 7.516,
            percentageChanges = 20.1
        ),
        Years(
            year = "1379",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 8.1),
                Month(month = "اردیبهشت", inflationIndex = 8.1),
                Month(month = "خرداد", inflationIndex = 8.3),
                Month(month = "تیر", inflationIndex = 8.2),
                Month(month = "مرداد", inflationIndex = 8.3),
                Month(month = "شهریور", inflationIndex = 8.3),
                Month(month = "مهر", inflationIndex = 8.4),
                Month(month = "آبان", inflationIndex = 8.5),
                Month(month = "آذر", inflationIndex = 8.7),
                Month(month = "دی", inflationIndex = 8.7),
                Month(month = "بهمن", inflationIndex = 8.8),
                Month(month = "اسفند", inflationIndex = 9.0),
            ),
            inflationIndex = 8.463,
            percentageChanges = 12.6
        ),
        Years(
            year = "1380",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 9.1),
                Month(month = "اردیبهشت", inflationIndex = 9.1),
                Month(month = "خرداد", inflationIndex = 9.2),
                Month(month = "تیر", inflationIndex = 9.2),
                Month(month = "مرداد", inflationIndex = 9.2),
                Month(month = "شهریور", inflationIndex = 9.3),
                Month(month = "مهر", inflationIndex = 9.3),
                Month(month = "آبان", inflationIndex = 9.4),
                Month(month = "آذر", inflationIndex = 9.6),
                Month(month = "دی", inflationIndex = 9.7),
                Month(month = "بهمن", inflationIndex = 9.8),
                Month(month = "اسفند", inflationIndex = 10.0),
            ),
            inflationIndex = 9.427,
            percentageChanges = 11.4
        ),
        Years(
            year = "1381",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 10.2),
                Month(month = "اردیبهشت", inflationIndex = 10.4),
                Month(month = "خرداد", inflationIndex = 10.6),
                Month(month = "تیر", inflationIndex = 10.6),
                Month(month = "مرداد", inflationIndex = 10.6),
                Month(month = "شهریور", inflationIndex = 10.8),
                Month(month = "مهر", inflationIndex = 10.8),
                Month(month = "آبان", inflationIndex = 11.0),
                Month(month = "آذر", inflationIndex = 11.2),
                Month(month = "دی", inflationIndex = 11.4),
                Month(month = "بهمن", inflationIndex = 11.6),
                Month(month = "اسفند", inflationIndex = 11.8),
            ),
            inflationIndex = 10.915,
            percentageChanges = 15.8
        ),
        Years(
            year = "1382",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 12.0),
                Month(month = "اردیبهشت", inflationIndex = 12.1),
                Month(month = "خرداد", inflationIndex = 12.3),
                Month(month = "تیر", inflationIndex = 12.4),
                Month(month = "مرداد", inflationIndex = 12.4),
                Month(month = "شهریور", inflationIndex = 12.4),
                Month(month = "مهر", inflationIndex = 12.5),
                Month(month = "آبان", inflationIndex = 12.7),
                Month(month = "آذر", inflationIndex = 12.9),
                Month(month = "دی", inflationIndex = 13.1),
                Month(month = "بهمن", inflationIndex = 13.2),
                Month(month = "اسفند", inflationIndex = 13.4),
            ),
            inflationIndex = 12.624,
            percentageChanges = 15.7
        ),
        Years(
            year = "1383",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 13.7),
                Month(month = "اردیبهشت", inflationIndex = 13.9),
                Month(month = "خرداد", inflationIndex = 14.1),
                Month(month = "تیر", inflationIndex = 14.3),
                Month(month = "مرداد", inflationIndex = 14.4),
                Month(month = "شهریور", inflationIndex = 14.4),
                Month(month = "مهر", inflationIndex = 14.6),
                Month(month = "آبان", inflationIndex = 14.7),
                Month(month = "آذر", inflationIndex = 14.8),
                Month(month = "دی", inflationIndex = 15.0),
                Month(month = "بهمن", inflationIndex = 15.2),
                Month(month = "اسفند", inflationIndex = 15.2),
            ),
            inflationIndex = 14.544,
            percentageChanges = 15.2
        ),
        Years(
            year = "1384",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 16.0),
                Month(month = "اردیبهشت", inflationIndex = 15.9),
                Month(month = "خرداد", inflationIndex = 15.8),
                Month(month = "تیر", inflationIndex = 15.7),
                Month(month = "مرداد", inflationIndex = 15.7),
                Month(month = "شهریور", inflationIndex = 15.8),
                Month(month = "مهر", inflationIndex = 15.9),
                Month(month = "آبان", inflationIndex = 16.0),
                Month(month = "آذر", inflationIndex = 16.2),
                Month(month = "دی", inflationIndex = 16.3),
                Month(month = "بهمن", inflationIndex = 16.5),
                Month(month = "اسفند", inflationIndex = 16.7),
            ),
            inflationIndex = 16.048,
            percentageChanges = 10.3
        ),
        Years(
            year = "1385",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 16.9),
                Month(month = "اردیبهشت", inflationIndex = 17.0),
                Month(month = "خرداد", inflationIndex = 19.3),
                Month(month = "تیر", inflationIndex = 19.3),
                Month(month = "مرداد", inflationIndex = 17.4),
                Month(month = "شهریور", inflationIndex = 17.7),
                Month(month = "مهر", inflationIndex = 17.9),
                Month(month = "آبان", inflationIndex = 18.1),
                Month(month = "آذر", inflationIndex = 18.5),
                Month(month = "دی", inflationIndex = 18.9),
                Month(month = "بهمن", inflationIndex = 19.2),
                Month(month = "اسفند", inflationIndex = 19.4),
            ),
            inflationIndex = 17.955,
            percentageChanges = 11.9
        ),
        Years(
            year = "1386",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 19.7),
                Month(month = "اردیبهشت", inflationIndex = 19.8),
                Month(month = "خرداد", inflationIndex = 20.1),
                Month(month = "تیر", inflationIndex = 20.2),
                Month(month = "مرداد", inflationIndex = 20.4),
                Month(month = "شهریور", inflationIndex = 20.9),
                Month(month = "مهر", inflationIndex = 21.2),
                Month(month = "آبان", inflationIndex = 21.6),
                Month(month = "آذر", inflationIndex = 22.2),
                Month(month = "دی", inflationIndex = 22.5),
                Month(month = "بهمن", inflationIndex = 23.0),
                Month(month = "اسفند", inflationIndex = 23.7),
            ),
            inflationIndex = 21.265,
            percentageChanges = 18.4
        ),
        Years(
            year = "1387",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 24.4),
                Month(month = "اردیبهشت", inflationIndex = 24.8),
                Month(month = "خرداد", inflationIndex = 25.4),
                Month(month = "تیر", inflationIndex = 25.5),
                Month(month = "مرداد", inflationIndex = 26.0),
                Month(month = "شهریور", inflationIndex = 27.0),
                Month(month = "مهر", inflationIndex = 27.5),
                Month(month = "آبان", inflationIndex = 27.7),
                Month(month = "آذر", inflationIndex = 28.0),
                Month(month = "دی", inflationIndex = 27.9),
                Month(month = "بهمن", inflationIndex = 27.8),
                Month(month = "اسفند", inflationIndex = 27.9),
            ),
            inflationIndex = 26.660,
            percentageChanges = 25.4
        ),
        Years(
            year = "1388",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 28.2),
                Month(month = "اردیبهشت", inflationIndex = 28.6),
                Month(month = "خرداد", inflationIndex = 29.1),
                Month(month = "تیر", inflationIndex = 29.1),
                Month(month = "مرداد", inflationIndex = 29.4),
                Month(month = "شهریور", inflationIndex = 29.5),
                Month(month = "مهر", inflationIndex = 29.6),
                Month(month = "آبان", inflationIndex = 29.7),
                Month(month = "آذر", inflationIndex = 30.1),
                Month(month = "دی", inflationIndex = 30.1),
                Month(month = "بهمن", inflationIndex = 30.3),
                Month(month = "اسفند", inflationIndex = 30.8),
            ),
            inflationIndex = 29.527,
            percentageChanges = 10.8
        ),
        Years(
            year = "1389",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 31.1),
                Month(month = "اردیبهشت", inflationIndex = 31.2),
                Month(month = "خرداد", inflationIndex = 31.5),
                Month(month = "تیر", inflationIndex = 31.8),
                Month(month = "مرداد", inflationIndex = 32.2),
                Month(month = "شهریور", inflationIndex = 32.5),
                Month(month = "مهر", inflationIndex = 33.1),
                Month(month = "آبان", inflationIndex = 33.4),
                Month(month = "آذر", inflationIndex = 33.9),
                Month(month = "دی", inflationIndex = 34.8),
                Month(month = "بهمن", inflationIndex = 35.7),
                Month(month = "اسفند", inflationIndex = 36.9),
            ),
            inflationIndex = 33.188,
            percentageChanges = 12.4
        ),
        Years(
            year = "1390",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 37.5),
                Month(month = "اردیبهشت", inflationIndex = 38.1),
                Month(month = "خرداد", inflationIndex = 38.6),
                Month(month = "تیر", inflationIndex = 38.7),
                Month(month = "مرداد", inflationIndex = 39.1),
                Month(month = "شهریور", inflationIndex = 39.8),
                Month(month = "مهر", inflationIndex = 40.2),
                Month(month = "آبان", inflationIndex = 40.8),
                Month(month = "آذر", inflationIndex = 41.4),
                Month(month = "دی", inflationIndex = 42.0),
                Month(month = "بهمن", inflationIndex = 43.1),
                Month(month = "اسفند", inflationIndex = 44.5),
            ),
            inflationIndex = 40.321,
            percentageChanges = 21.5
        ),
        Years(
            year = "1391",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 45.5),
                Month(month = "اردیبهشت", inflationIndex = 46.6),
                Month(month = "خرداد", inflationIndex = 47.1),
                Month(month = "تیر", inflationIndex = 48.1),
                Month(month = "مرداد", inflationIndex = 48.9),
                Month(month = "شهریور", inflationIndex = 50.3),
                Month(month = "مهر", inflationIndex = 52.7),
                Month(month = "آبان", inflationIndex = 55.2),
                Month(month = "آذر", inflationIndex = 56.4),
                Month(month = "دی", inflationIndex = 57.5),
                Month(month = "بهمن", inflationIndex = 60.5),
                Month(month = "اسفند", inflationIndex = 62.9),
            ),
            inflationIndex = 52.635,
            percentageChanges = 30.5
        ),
        Years(
            year = "1392",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 64.7),
                Month(month = "اردیبهشت", inflationIndex = 66.0),
                Month(month = "خرداد", inflationIndex = 68.3),
                Month(month = "تیر", inflationIndex = 69.2),
                Month(month = "مرداد", inflationIndex = 70.0),
                Month(month = "شهریور", inflationIndex = 71.2),
                Month(month = "مهر", inflationIndex = 72.1),
                Month(month = "آبان", inflationIndex = 72.8),
                Month(month = "آذر", inflationIndex = 73.1),
                Month(month = "دی", inflationIndex = 74.0),
                Month(month = "بهمن", inflationIndex = 74.3),
                Month(month = "اسفند", inflationIndex = 75.2),
            ),
            inflationIndex = 70.916,
            percentageChanges = 34.7
        ),
        Years(
            year = "1393",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 76.0),
                Month(month = "اردیبهشت", inflationIndex = 76.9),
                Month(month = "خرداد", inflationIndex = 78.2),
                Month(month = "تیر", inflationIndex = 79.3),
                Month(month = "مرداد", inflationIndex = 80.4),
                Month(month = "شهریور", inflationIndex = 81.4),
                Month(month = "مهر", inflationIndex = 82.6),
                Month(month = "آبان", inflationIndex = 83.8),
                Month(month = "آذر", inflationIndex = 85.4),
                Month(month = "دی", inflationIndex = 85.6),
                Month(month = "بهمن", inflationIndex = 86.3),
                Month(month = "اسفند", inflationIndex = 87.4),
            ),
            inflationIndex = 81.948,
            percentageChanges = 15.6
        ),
        Years(
            year = "1394",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 88.5),
                Month(month = "اردیبهشت", inflationIndex = 89.4),
                Month(month = "خرداد", inflationIndex = 90.9),
                Month(month = "تیر", inflationIndex = 90.6),
                Month(month = "مرداد", inflationIndex = 90.5),
                Month(month = "شهریور", inflationIndex = 91.0),
                Month(month = "مهر", inflationIndex = 91.5),
                Month(month = "آبان", inflationIndex = 92.2),
                Month(month = "آذر", inflationIndex = 93.4),
                Month(month = "دی", inflationIndex = 93.8),
                Month(month = "بهمن", inflationIndex = 94.0),
                Month(month = "اسفند", inflationIndex = 94.7),
            ),
            inflationIndex = 91.714,
            percentageChanges = 11.9
        ),
        Years(
            year = "1395",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 95.0),
                Month(month = "اردیبهشت", inflationIndex = 96.3),
                Month(month = "خرداد", inflationIndex = 97.7),
                Month(month = "تیر", inflationIndex = 98.3),
                Month(month = "مرداد", inflationIndex = 99.2),
                Month(month = "شهریور", inflationIndex = 99.6),
                Month(month = "مهر", inflationIndex = 100.0),
                Month(month = "آبان", inflationIndex = 100.2),
                Month(month = "آذر", inflationIndex = 101.7),
                Month(month = "دی", inflationIndex = 102.5),
                Month(month = "بهمن", inflationIndex = 103.7),
                Month(month = "اسفند", inflationIndex = 105.9),
            ),
            inflationIndex = 100.0,
            percentageChanges = 9.0
        ),
        Years(
            year = "1396",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 107.1),
                Month(month = "اردیبهشت", inflationIndex = 107.1),
                Month(month = "خرداد", inflationIndex = 107.8),
                Month(month = "تیر", inflationIndex = 107.5),
                Month(month = "مرداد", inflationIndex = 107.7),
                Month(month = "شهریور", inflationIndex = 108.0),
                Month(month = "مهر", inflationIndex = 108.4),
                Month(month = "آبان", inflationIndex = 109.8),
                Month(month = "آذر", inflationIndex = 111.9),
                Month(month = "دی", inflationIndex = 112.4),
                Month(month = "بهمن", inflationIndex = 113.4),
                Month(month = "اسفند", inflationIndex = 114.7),
            ),
            inflationIndex = 109.650,
            percentageChanges = 9.7
        ),
        Years(
            year = "1397",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 115.6),
                Month(month = "اردیبهشت", inflationIndex = 117.5),
                Month(month = "خرداد", inflationIndex = 122.6),
                Month(month = "تیر", inflationIndex = 126.8),
                Month(month = "مرداد", inflationIndex = 133.8),
                Month(month = "شهریور", inflationIndex = 141.9),
                Month(month = "مهر", inflationIndex = 148.4),
                Month(month = "آبان", inflationIndex = 153.6),
                Month(month = "آذر", inflationIndex = 159.3),
                Month(month = "دی", inflationIndex = 162.1),
                Month(month = "بهمن", inflationIndex = 167.7),
                Month(month = "اسفند", inflationIndex =176.8 ),
            ),
            inflationIndex = 143.842,
            percentageChanges = 31.2
        ),
        Years(
            year = "1398",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 182.7),
                Month(month = "اردیبهشت", inflationIndex = 188.0),
                Month(month = "خرداد", inflationIndex = 192.6),
                Month(month = "تیر", inflationIndex = 196.9),
                Month(month = "مرداد", inflationIndex = 198.5),
                Month(month = "شهریور", inflationIndex = 200.1),
                Month(month = "مهر", inflationIndex = 201.4),
                Month(month = "آبان", inflationIndex = 204.1),
                Month(month = "آذر", inflationIndex = 212.5),
                Month(month = "دی", inflationIndex = 214.7),
                Month(month = "بهمن", inflationIndex = 219.5),
                Month(month = "اسفند", inflationIndex = 226.5),
            ),
            inflationIndex = 203.150,
            percentageChanges = 41.2
        ),
        Years(
            year = "1399",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 229.9),
                Month(month = "اردیبهشت", inflationIndex = 240.2),
                Month(month = "خرداد", inflationIndex = 249.8),
                Month(month = "تیر", inflationIndex = 261.8),
                Month(month = "مرداد", inflationIndex = 270.8),
                Month(month = "شهریور", inflationIndex = 281.3),
                Month(month = "مهر", inflationIndex = 302.8),
                Month(month = "آبان", inflationIndex = 326.1),
                Month(month = "آذر", inflationIndex = 338.9),
                Month(month = "دی", inflationIndex = 347.5),
                Month(month = "بهمن", inflationIndex = 363.0),
                Month(month = "اسفند", inflationIndex = 374.2),
            ),
            inflationIndex = 298.858,
            percentageChanges = 47.1
        ),
        Years(
            year = "1400",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 378.3),
                Month(month = "اردیبهشت", inflationIndex = 382.0),
                Month(month = "خرداد", inflationIndex = 399.3),
                Month(month = "تیر", inflationIndex = 410.0),
                Month(month = "مرداد", inflationIndex = 421.7),
                Month(month = "شهریور", inflationIndex = 435.6),
                Month(month = "مهر", inflationIndex = 448.9),
                Month(month = "آبان", inflationIndex = 459.7),
                Month(month = "آذر", inflationIndex = 468.2),
                Month(month = "دی", inflationIndex = 474.2),
                Month(month = "بهمن", inflationIndex = 482.0),
                Month(month = "اسفند", inflationIndex = 484.6),
            ),
            inflationIndex = 437.042,
            percentageChanges = 46.2
        ),
        Years(
            year = "1401",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 495.1),
                Month(month = "اردیبهشت", inflationIndex = 520.4),
                Month(month = "خرداد", inflationIndex = 575.4),
                Month(month = "تیر", inflationIndex = 600.4),
                Month(month = "مرداد", inflationIndex = 614.8),
                Month(month = "شهریور", inflationIndex = 631.0),
                Month(month = "مهر", inflationIndex = 649.5),
                Month(month = "آبان", inflationIndex = 663.5),
                Month(month = "آذر", inflationIndex = 679.8),
                Month(month = "دی", inflationIndex = 713.4),
                Month(month = "بهمن", inflationIndex = 745.1),
                Month(month = "اسفند", inflationIndex = 794.3),
            ),
            inflationIndex = 640.225,
            percentageChanges = 46.5
        ),
        Years(
            year = "1402",
            months = listOf(
                Month(month = "فروردین", inflationIndex = 834.9)
            ),
            inflationIndex = null,
            percentageChanges = null
        )
    )
}

data class Years(
    val year: String,
    val months: List<Month>,
    val inflationIndex: Double?,
    val percentageChanges: Double?
)

data class Month(
    val month: String,
    val inflationIndex: Double
)